/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1/resources.proto

package com.google.cloud.contactcenterinsights.v1;

public final class ResourcesProto {
  private ResourcesProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_DialogflowSegmentMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_DialogflowSegmentMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Analysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_GcsSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Entity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Intent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SilenceData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_HoldData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SentimentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Issue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "5google/cloud/contactcenterinsights/v1/resources.proto\022%google.cloud.contactcen"
          + "terinsights.v1\032\037google/api/field_behavio"
          + "r.proto\032\031google/api/resource.proto\032\036goog"
          + "le/protobuf/duration.proto\032\037google/protobuf/timestamp.proto\032\034google/api/annotations.proto\"\225\023\n"
          + "\014Conversation\022Y\n\r"
          + "call_metadata\030\007"
          + " \001(\0132@.google.cloud.contactcenterinsights.v1.Conversation.CallMetadataH\000\0221\n"
          + "\013expire_time\030\017 \001(\0132\032.google.protobuf.TimestampH\001\022-\n"
          + "\003ttl\030\020 \001(\0132\031.google.protobuf.DurationB\003\340A\004H\001\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\022R\n"
          + "\013data_source\030\002"
          + " \001(\0132=.google.cloud.contactcenterinsights.v1.ConversationDataSource\0224\n"
          + "\013create_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\004"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022.\n\n"
          + "start_time\030\021 \001(\0132\032.google.protobuf.Timestamp\022\025\n\r"
          + "language_code\030\016 \001(\t\022\020\n"
          + "\010agent_id\030\005 \001(\t\022O\n"
          + "\006labels\030\006"
          + " \003(\0132?.google.cloud.contactcenterinsights.v1.Conversation.LabelsEntry\022W\n\n"
          + "transcript\030\010"
          + " \001(\0132>.google.cloud.contactcenterinsights.v1.Conversation.TranscriptB\003\340A\003\022O\n"
          + "\006medium\030\t"
          + " \001(\0162:.google.cloud.contactcenterinsights.v1.Conversation.MediumB\003\340A\005\0220\n"
          + "\010duration\030\n"
          + " \001(\0132\031.google.protobuf.DurationB\003\340A\003\022\027\n\n"
          + "turn_count\030\013 \001(\005B\003\340A\003\022M\n"
          + "\017latest_analysis\030\014"
          + " \001(\0132/.google.cloud.contactcenterinsights.v1.AnalysisB\003\340A\003\022Z\n"
          + "\023runtime_annotations\030\r"
          + " \003(\01328.google.cloud.contactcenterinsights.v1.RuntimeAnnotationB\003\340A\003\022k\n"
          + "\022dialogflow_intents\030\022"
          + " \003(\0132J.google.cloud.contactcenterinsights.v1.Conversation.DialogflowIntentsEntryB\003\340A\003\032?\n"
          + "\014CallMetadata\022\030\n"
          + "\020customer_channel\030\001 \001(\005\022\025\n\r"
          + "agent_channel\030\002 \001(\005\032\206\007\n\n"
          + "Transcript\022m\n"
          + "\023transcript_segments\030\001"
          + " \003(\0132P.google.cloud.contactcenterinsights.v1.Conversation.Transcript.TranscriptSegment\032\210\006\n"
          + "\021TranscriptSegment\0220\n"
          + "\014message_time\030\006 \001(\0132\032.google.protobuf.Timestamp\022\014\n"
          + "\004text\030\001 \001(\t\022\022\n\n"
          + "confidence\030\002 \001(\002\022h\n"
          + "\005words\030\003"
          + " \003(\0132Y.google.cloud.contactcenterinsights.v1.Conversation.Transcript.TranscriptSegment.WordInfo\022\025\n\r"
          + "language_code\030\004 \001(\t\022\023\n"
          + "\013channel_tag\030\005 \001(\005\022[\n"
          + "\023segment_participant\030\t"
          + " \001(\0132>.google.cloud.contactcenterinsights.v1.ConversationParticipant\022\217\001\n"
          + "\033dialogflow_segment_metadata\030\n"
          + " \001(\0132j.google.cloud.contactcenterinsights.v1.Conversation.Transcript.TranscriptSegment.DialogflowSegmentMetadata\022G\n"
          + "\tsentiment\030\013"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.SentimentData\032\214\001\n"
          + "\010WordInfo\022/\n"
          + "\014start_offset\030\001 \001(\0132\031.google.protobuf.Duration\022-\n\n"
          + "end_offset\030\002 \001(\0132\031.google.protobuf.Duration\022\014\n"
          + "\004word\030\003 \001(\t\022\022\n\n"
          + "confidence\030\004 \001(\002\032B\n"
          + "\031DialogflowSegmentMetadata\022%\n"
          + "\035smart_reply_allowlist_covered\030\001 \001(\010\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\032q\n"
          + "\026DialogflowIntentsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022F\n"
          + "\005value\030\002"
          + " \001(\01327.google.cloud.contactcenterinsights.v1.DialogflowIntent:\0028\001\":\n"
          + "\006Medium\022\026\n"
          + "\022MEDIUM_UNSPECIFIED\020\000\022\016\n\n"
          + "PHONE_CALL\020\001\022\010\n"
          + "\004CHAT\020\002:|\352Ay\n"
          + "1contactcenterinsights.googleapis.com/Conversation\022Dprojects/{project}/locations/{location}/conversations/{conversation}B\n\n"
          + "\010metadataB\014\n\n"
          + "expiration\"\357\002\n"
          + "\010Analysis\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\0225\n"
          + "\014request_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013create_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022S\n"
          + "\017analysis_result\030\007"
          + " \001(\01325.google.cloud.contactcenterinsights.v1.AnalysisResultB\003\340A\003:\215\001\352A\211\001\n"
          + "-contactcenterinsights.googleapis.com/Analysis\022Xprojects/{project}/locations/{location}/conversations/{conversation}/analyses/{analysis}\"\300\001\n"
          + "\026ConversationDataSource\022F\n\n"
          + "gcs_source\030\001"
          + " \001(\01320.google.cloud.contactcenterinsights.v1.GcsSourceH\000\022T\n"
          + "\021dialogflow_source\030\003"
          + " \001(\01327.google.cloud.contactcenterinsights.v1.DialogflowSourceH\000B\010\n"
          + "\006source\";\n"
          + "\tGcsSource\022\021\n"
          + "\taudio_uri\030\001 \001(\t\022\033\n"
          + "\016transcript_uri\030\002 \001(\tB\003\340A\005\"K\n"
          + "\020DialogflowSource\022$\n"
          + "\027dialogflow_conversation\030\001 \001(\tB\003\340A\003\022\021\n"
          + "\taudio_uri\030\003 \001(\t\"\306\010\n"
          + "\016AnalysisResult\022l\n"
          + "\026call_analysis_metadata\030\002"
          + " \001(\0132J.google.cloud.contactcenterinsights.v1.AnalysisResult.CallAnalysisMetadataH\000\022,\n"
          + "\010end_time\030\001 \001(\0132\032.google.protobuf.Timestamp\032\213\007\n"
          + "\024CallAnalysisMetadata\022J\n"
          + "\013annotations\030\002"
          + " \003(\01325.google.cloud.contactcenterinsights.v1.CallAnnotation\022j\n"
          + "\010entities\030\003"
          + " \003(\0132X.google.cloud.contactcenterinsights.v1.AnalysisResult.CallAnalysisMetadata.EntitiesEntry\022U\n\n"
          + "sentiments\030\004"
          + " \003(\0132A.google.cloud.contactcenterinsights.v1.ConversationLevelSentiment\022h\n"
          + "\007intents\030\006"
          + " \003(\0132W.google.cloud.contactcenterinsights.v1.AnalysisResult.CallAnalysisMetadata.IntentsEntry\022w\n"
          + "\017phrase_matchers\030\007"
          + " \003(\0132^.google.cloud.contactcenterinsights.v1.AnalysisResult.CallAnalysisMetadata.PhraseMatchersEntry\022S\n"
          + "\022issue_model_result\030\010"
          + " \001(\01327.google.cloud.contactcenterinsights.v1.IssueModelResult\032^\n\r"
          + "EntitiesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022<\n"
          + "\005value\030\002"
          + " \001(\0132-.google.cloud.contactcenterinsights.v1.Entity:\0028\001\032]\n"
          + "\014IntentsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022<\n"
          + "\005value\030\002"
          + " \001(\0132-.google.cloud.contactcenterinsights.v1.Intent:\0028\001\032m\n"
          + "\023PhraseMatchersEntry\022\013\n"
          + "\003key\030\001 \001(\t\022E\n"
          + "\005value\030\002"
          + " \001(\01326.google.cloud.contactcenterinsights.v1.PhraseMatchData:\0028\001B\n\n"
          + "\010metadata\"o\n"
          + "\020IssueModelResult\022\023\n"
          + "\013issue_model\030\001 \001(\t\022F\n"
          + "\006issues\030\002"
          + " \003(\01326.google.cloud.contactcenterinsights.v1.IssueAssignment\"\177\n"
          + "\032ConversationLevelSentiment\022\023\n"
          + "\013channel_tag\030\001 \001(\005\022L\n"
          + "\016sentiment_data\030\002"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.SentimentData\"J\n"
          + "\017IssueAssignment\022\r\n"
          + "\005issue\030\001 \001(\t\022\r\n"
          + "\005score\030\002 \001(\001\022\031\n"
          + "\014display_name\030\003 \001(\tB\003\340A\005\"\242\006\n"
          + "\016CallAnnotation\022T\n"
          + "\021interruption_data\030\n"
          + " \001(\01327.google.cloud.contactcenterinsights.v1.InterruptionDataH\000\022N\n"
          + "\016sentiment_data\030\013"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.SentimentDataH\000\022J\n"
          + "\014silence_data\030\014"
          + " \001(\01322.google.cloud.contactcenterinsights.v1.SilenceDataH\000\022D\n"
          + "\thold_data\030\r"
          + " \001(\0132/.google.cloud.contactcenterinsights.v1.HoldDataH\000\022W\n"
          + "\023entity_mention_data\030\017"
          + " \001(\01328.google.cloud.contactcenterinsights.v1.EntityMentionDataH\000\022S\n"
          + "\021intent_match_data\030\020"
          + " \001(\01326.google.cloud.contactcenterinsights.v1.IntentMatchDataH\000\022S\n"
          + "\021phrase_match_data\030\021"
          + " \001(\01326.google.cloud.contactcenterinsights.v1.PhraseMatchDataH\000\022\023\n"
          + "\013channel_tag\030\001 \001(\005\022\\\n"
          + "\031annotation_start_boundary\030\004"
          + " \001(\01329.google.cloud.contactcenterinsights.v1.AnnotationBoundary\022Z\n"
          + "\027annotation_end_boundary\030\005"
          + " \001(\01329.google.cloud.contactcenterinsights.v1.AnnotationBoundaryB\006\n"
          + "\004data\"Y\n"
          + "\022AnnotationBoundary\022\024\n\n"
          + "word_index\030\003 \001(\005H\000\022\030\n"
          + "\020transcript_index\030\001 \001(\005B\023\n"
          + "\021detailed_boundary\"\200\004\n"
          + "\006Entity\022\024\n"
          + "\014display_name\030\001 \001(\t\022@\n"
          + "\004type\030\002 \001(\01622.google.cloud.contactcenterinsights.v1.Entity.Type\022M\n"
          + "\010metadata\030\003"
          + " \003(\0132;.google.cloud.contactcenterinsights.v1.Entity.MetadataEntry\022\020\n"
          + "\010salience\030\004 \001(\002\022G\n"
          + "\tsentiment\030\005"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.SentimentData\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\302\001\n"
          + "\004Type\022\024\n"
          + "\020TYPE_UNSPECIFIED\020\000\022\n\n"
          + "\006PERSON\020\001\022\014\n"
          + "\010LOCATION\020\002\022\020\n"
          + "\014ORGANIZATION\020\003\022\t\n"
          + "\005EVENT\020\004\022\017\n"
          + "\013WORK_OF_ART\020\005\022\021\n\r"
          + "CONSUMER_GOOD\020\006\022\t\n"
          + "\005OTHER\020\007\022\020\n"
          + "\014PHONE_NUMBER\020\t\022\013\n"
          + "\007ADDRESS\020\n"
          + "\022\010\n"
          + "\004DATE\020\013\022\n\n"
          + "\006NUMBER\020\014\022\t\n"
          + "\005PRICE\020\r"
          + "\"*\n"
          + "\006Intent\022\n\n"
          + "\002id\030\001 \001(\t\022\024\n"
          + "\014display_name\030\002 \001(\t\"?\n"
          + "\017PhraseMatchData\022\026\n"
          + "\016phrase_matcher\030\001 \001(\t\022\024\n"
          + "\014display_name\030\002 \001(\t\"(\n"
          + "\020DialogflowIntent\022\024\n"
          + "\014display_name\030\001 \001(\t\"\022\n"
          + "\020InterruptionData\"\r\n"
          + "\013SilenceData\"\n\n"
          + "\010HoldData\"\217\002\n"
          + "\021EntityMentionData\022\030\n"
          + "\020entity_unique_id\030\001 \001(\t\022R\n"
          + "\004type\030\002"
          + " \001(\0162D.google.cloud.contactcenterinsights.v1.EntityMentionData.MentionType\022G\n"
          + "\tsentiment\030\003"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.SentimentData\"C\n"
          + "\013MentionType\022\034\n"
          + "\030MENTION_TYPE_UNSPECIFIED\020\000\022\n\n"
          + "\006PROPER\020\001\022\n\n"
          + "\006COMMON\020\002\"+\n"
          + "\017IntentMatchData\022\030\n"
          + "\020intent_unique_id\030\001 \001(\t\"1\n\r"
          + "SentimentData\022\021\n"
          + "\tmagnitude\030\001 \001(\002\022\r\n"
          + "\005score\030\002 \001(\002\"\255\006\n\n"
          + "IssueModel\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\022\024\n"
          + "\014display_name\030\002 \001(\t\0224\n"
          + "\013create_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\004 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022K\n"
          + "\005state\030\005"
          + " \001(\01627.google.cloud.contactcenterinsights.v1.IssueModel.StateB\003\340A\003\022\\\n"
          + "\021input_data_config\030\006"
          + " \001(\0132A.google.cloud.contactcenterinsights.v1.IssueModel.InputDataConfig\022[\n"
          + "\016training_stats\030\007"
          + " \001(\0132;.google.cloud.contactcenterinsights.v1.IssueModelLabelStatsB\006\340A\003\340A\005\032\234\001\n"
          + "\017InputDataConfig\022N\n"
          + "\006medium\030\001"
          + " \001(\0162:.google.cloud.contactcenterinsights.v1.Conversation.MediumB\002\030\001\022)\n"
          + "\034training_conversations_count\030\002 \001(\003B\003\340A\003\022\016\n"
          + "\006filter\030\003 \001(\t\"j\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\016\n\n"
          + "UNDEPLOYED\020\001\022\r\n"
          + "\tDEPLOYING\020\002\022\014\n"
          + "\010DEPLOYED\020\003\022\017\n"
          + "\013UNDEPLOYING\020\004\022\014\n"
          + "\010DELETING\020\005:w\352At\n"
          + "/contactcenterinsights.googleapis.com/IssueModel\022Aprojects/{project}/locations/{location}/issueModels/{issue_model}\"\240\002\n"
          + "\005Issue\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\022\024\n"
          + "\014display_name\030\002 \001(\t\0224\n"
          + "\013create_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\004"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003:\201\001\352A~\n"
          + "*contactcenterinsights.googleapis.com/Issue\022Pprojects/{project}/locations/{location}/issueModels/{issue_model}/issues/{issue}\"\233\003\n"
          + "\024IssueModelLabelStats\022$\n"
          + "\034analyzed_conversations_count\030\001 \001(\003\022(\n"
          + " unclassified_conversations_count\030\002 \001(\003\022`\n"
          + "\013issue_stats\030\003"
          + " \003(\0132K.google.cloud.contactcenterinsights.v1.IssueModelLabelStats.IssueStatsEntry\032V\n\n"
          + "IssueStats\022\r\n"
          + "\005issue\030\001 \001(\t\022#\n"
          + "\033labeled_conversations_count\030\002 \001(\003\022\024\n"
          + "\014display_name\030\003 \001(\t\032y\n"
          + "\017IssueStatsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022U\n"
          + "\005value\030\002"
          + " \001(\0132F.google.cloud.contactcenterinsights.v1.IssueModelLabelStats.IssueStats:\0028\001\"\223\006\n\r"
          + "PhraseMatcher\022\014\n"
          + "\004name\030\001 \001(\t\022\033\n"
          + "\013revision_id\030\002 \001(\tB\006\340A\005\340A\003\022\023\n"
          + "\013version_tag\030\003 \001(\t\022=\n"
          + "\024revision_create_time\030\004"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022\024\n"
          + "\014display_name\030\005 \001(\t\022Y\n"
          + "\004type\030\006"
          + " \001(\0162F.google.cloud.contactcenterinsights.v1.PhraseMatcher.PhraseMatcherTypeB\003\340A\002\022\016\n"
          + "\006active\030\007 \001(\010\022]\n"
          + "\030phrase_match_rule_groups\030\010"
          + " \003(\0132;.google.cloud.contactcenterinsights.v1.PhraseMatchRuleGroup\022?\n"
          + "\026activation_update_time\030\t"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022W\n"
          + "\n"
          + "role_match\030\n"
          + " \001(\0162C.google.cloud.contactcenterinsights.v1.ConversationParticipant.Role\0224\n"
          + "\013update_time\030\013 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\"P\n"
          + "\021PhraseMatcherType\022#\n"
          + "\037PHRASE_MATCHER_TYPE_UNSPECIFIED\020\000\022\n"
          + "\n"
          + "\006ALL_OF\020\001\022\n\n"
          + "\006ANY_OF\020\002:\200\001\352A}\n"
          + "2contactcenterinsights.googleapis.com/PhraseMatcher\022Gprojects/{project}/locations/{location}/phraseMatchers/{phrase_matcher}\"\265\002\n"
          + "\024PhraseMatchRuleGroup\022g\n"
          + "\004type\030\001"
          + " \001(\0162T.google.cloud.contactcenterinsights.v1.PhraseMatchRuleGroup.PhraseMatchRuleGroupTypeB\003\340A\002\022R\n"
          + "\022phrase_match_rules\030\002"
          + " \003(\01326.google.cloud.contactcenterinsights.v1.PhraseMatchRule\"`\n"
          + "\030PhraseMatchRuleGroupType\022,\n"
          + "(PHRASE_MATCH_RULE_GROUP_TYPE_UNSPECIFIED\020\000\022\n\n"
          + "\006ALL_OF\020\001\022\n\n"
          + "\006ANY_OF\020\002\"\204\001\n"
          + "\017PhraseMatchRule\022\022\n"
          + "\005query\030\001 \001(\tB\003\340A\002\022\017\n"
          + "\007negated\030\002 \001(\010\022L\n"
          + "\006config\030\003"
          + " \001(\0132<.google.cloud.contactcenterinsights.v1.PhraseMatchRuleConfig\"x\n"
          + "\025PhraseMatchRuleConfig\022U\n"
          + "\022exact_match_config\030\001"
          + " \001(\01327.google.cloud.contactcenterinsights.v1.ExactMatchConfigH\000B\010\n"
          + "\006config\"*\n"
          + "\020ExactMatchConfig\022\026\n"
          + "\016case_sensitive\030\001 \001(\010\"\221\005\n"
          + "\010Settings\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\0224\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\003"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022\025\n\r"
          + "language_code\030\004 \001(\t\0223\n"
          + "\020conversation_ttl\030\005 \001(\0132\031.google.protobuf.Duration\022u\n"
          + "\034pubsub_notification_settings\030\006"
          + " \003(\0132O.google.cloud.contactcenterinsights.v1.Settings.PubsubNotificationSettingsEntry\022W\n"
          + "\017analysis_config\030\007"
          + " \001(\0132>.google.cloud.contactcenterinsights.v1.Settings.AnalysisConfig\032A\n"
          + "\016AnalysisConfig\022/\n"
          + "\'runtime_integration_analysis_percentage\030\001 \001(\001\032A\n"
          + "\037PubsubNotificationSettingsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001:d\352Aa\n"
          + "-contactcenterinsights.googleapis.com/Settings\0220projects/{project}/locations/{location}/settings\"\230\006\n"
          + "\021RuntimeAnnotation\022Z\n"
          + "\022article_suggestion\030\006"
          + " \001(\0132<.google.cloud.contactcenterinsights.v1.ArticleSuggestionDataH\000\022J\n\n"
          + "faq_answer\030\007"
          + " \001(\01324.google.cloud.contactcenterinsights.v1.FaqAnswerDataH\000\022L\n"
          + "\013smart_reply\030\010"
          + " \001(\01325.google.cloud.contactcenterinsights.v1.SmartReplyDataH\000\022e\n"
          + "\030smart_compose_suggestion\030\t"
          + " \001(\0132A.google.cloud.contactcenterinsights.v1.SmartComposeSuggestionDataH\000\022b\n"
          + "\026dialogflow_interaction\030\n"
          + " \001(\0132@.google.cloud.contactcenterinsights.v1.DialogflowInteractionDataH\000\022\025\n\r"
          + "annotation_id\030\001 \001(\t\022/\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022Q\n"
          + "\016start_boundary\030\003"
          + " \001(\01329.google.cloud.contactcenterinsights.v1.AnnotationBoundary\022O\n"
          + "\014end_boundary\030\004"
          + " \001(\01329.google.cloud.contactcenterinsights.v1.AnnotationBoundary\022N\n"
          + "\017answer_feedback\030\005"
          + " \001(\01325.google.cloud.contactcenterinsights.v1.AnswerFeedbackB\006\n"
          + "\004data\"\211\002\n"
          + "\016AnswerFeedback\022a\n"
          + "\021correctness_level\030\001"
          + " \001(\0162F.google.cloud.contactcenterinsights.v1.AnswerFeedback.CorrectnessLevel\022\017\n"
          + "\007clicked\030\002 \001(\010\022\021\n"
          + "\tdisplayed\030\003 \001(\010\"p\n"
          + "\020CorrectnessLevel\022!\n"
          + "\035CORRECTNESS_LEVEL_UNSPECIFIED\020\000\022\017\n"
          + "\013NOT_CORRECT\020\001\022\025\n"
          + "\021PARTIALLY_CORRECT\020\002\022\021\n\r"
          + "FULLY_CORRECT\020\003\"\202\002\n"
          + "\025ArticleSuggestionData\022\r\n"
          + "\005title\030\001 \001(\t\022\013\n"
          + "\003uri\030\002 \001(\t\022\030\n"
          + "\020confidence_score\030\003 \001(\002\022\\\n"
          + "\010metadata\030\004"
          + " \003(\0132J.google.cloud.contactcenterinsights.v1.ArticleSuggestionData.MetadataEntry\022\024\n"
          + "\014query_record\030\005 \001(\t\022\016\n"
          + "\006source\030\006 \001(\t\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\370\001\n\r"
          + "FaqAnswerData\022\016\n"
          + "\006answer\030\001 \001(\t\022\030\n"
          + "\020confidence_score\030\002 \001(\002\022\020\n"
          + "\010question\030\003 \001(\t\022T\n"
          + "\010metadata\030\004"
          + " \003(\0132B.google.cloud.contactcenterinsights.v1.FaqAnswerData.MetadataEntry\022\024\n"
          + "\014query_record\030\005 \001(\t\022\016\n"
          + "\006source\030\006 \001(\t\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\327\001\n"
          + "\016SmartReplyData\022\r\n"
          + "\005reply\030\001 \001(\t\022\030\n"
          + "\020confidence_score\030\002 \001(\001\022U\n"
          + "\010metadata\030\003"
          + " \003(\0132C.google.cloud.contactcenterinsights.v1.SmartReplyData.MetadataEntry\022\024\n"
          + "\014query_record\030\004 \001(\t\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\364\001\n"
          + "\032SmartComposeSuggestionData\022\022\n\n"
          + "suggestion\030\001 \001(\t\022\030\n"
          + "\020confidence_score\030\002 \001(\001\022a\n"
          + "\010metadata\030\003"
          + " \003(\0132O.google.cloud.contactcenterinsights.v1.SmartComposeSuggestionData.MetadataEntry\022\024\n"
          + "\014query_record\030\004 \001(\t\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"M\n"
          + "\031DialogflowInteractionData\022\034\n"
          + "\024dialogflow_intent_id\030\001 \001(\t\022\022\n\n"
          + "confidence\030\002 \001(\002\"\213\003\n"
          + "\027ConversationParticipant\022Q\n"
          + "\033dialogflow_participant_name\030\005 \001(\tB*\372A\'\n"
          + "%dialogflow.googleapis.com/ParticipantH\000\022\021\n"
          + "\007user_id\030\006 \001(\tH\000\022\"\n"
          + "\026dialogflow_participant\030\001 \001(\tB\002\030\001\022#\n"
          + "\033obfuscated_external_user_id\030\003 \001(\t\022Q\n"
          + "\004role\030\002"
          + " \001(\0162C.google.cloud.contactcenterinsights.v1.ConversationParticipant.Role\"_\n"
          + "\004Role\022\024\n"
          + "\020ROLE_UNSPECIFIED\020\000\022\017\n"
          + "\013HUMAN_AGENT\020\001\022\023\n"
          + "\017AUTOMATED_AGENT\020\002\022\014\n"
          + "\010END_USER\020\003\022\r\n"
          + "\tANY_AGENT\020\004B\r\n"
          + "\013participantB\354\003\n"
          + ")com.google.cloud.contactcenterinsights.v1B\016Resources"
          + "ProtoP\001ZZgoogle.golang.org/genproto/googleapis/cloud/contactcenterinsights/v1;co"
          + "ntactcenterinsights\252\002%Google.Cloud.Conta"
          + "ctCenterInsights.V1\312\002%Google\\Cloud\\ContactCenterInsights\\V1\352\002(Google::Cloud::ContactCenterInsights::V1\352A\324\001\n"
          + "%dialogflow.googleapis.com/Participant\022Jprojects/{pro"
          + "ject}/conversations/{conversation}/participants/{participant}\022_projects/{project"
          + "}/locations/{location}/conversations/{conversation}/participants/{participant}b\006"
          + "proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor,
            new java.lang.String[] {
              "CallMetadata",
              "ExpireTime",
              "Ttl",
              "Name",
              "DataSource",
              "CreateTime",
              "UpdateTime",
              "StartTime",
              "LanguageCode",
              "AgentId",
              "Labels",
              "Transcript",
              "Medium",
              "Duration",
              "TurnCount",
              "LatestAnalysis",
              "RuntimeAnnotations",
              "DialogflowIntents",
              "Metadata",
              "Expiration",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor,
            new java.lang.String[] {
              "CustomerChannel", "AgentChannel",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor,
            new java.lang.String[] {
              "TranscriptSegments",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor,
            new java.lang.String[] {
              "MessageTime",
              "Text",
              "Confidence",
              "Words",
              "LanguageCode",
              "ChannelTag",
              "SegmentParticipant",
              "DialogflowSegmentMetadata",
              "Sentiment",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor,
            new java.lang.String[] {
              "StartOffset", "EndOffset", "Word", "Confidence",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_DialogflowSegmentMetadata_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_DialogflowSegmentMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_DialogflowSegmentMetadata_descriptor,
            new java.lang.String[] {
              "SmartReplyAllowlistCovered",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Analysis_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor,
            new java.lang.String[] {
              "Name", "RequestTime", "CreateTime", "AnalysisResult",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor,
            new java.lang.String[] {
              "GcsSource", "DialogflowSource", "Source",
            });
    internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_contactcenterinsights_v1_GcsSource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor,
            new java.lang.String[] {
              "AudioUri", "TranscriptUri",
            });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor,
            new java.lang.String[] {
              "DialogflowConversation", "AudioUri",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor,
            new java.lang.String[] {
              "CallAnalysisMetadata", "EndTime", "Metadata",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor,
            new java.lang.String[] {
              "Annotations",
              "Entities",
              "Sentiments",
              "Intents",
              "PhraseMatchers",
              "IssueModelResult",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor,
            new java.lang.String[] {
              "IssueModel", "Issues",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor,
            new java.lang.String[] {
              "ChannelTag", "SentimentData",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor,
            new java.lang.String[] {
              "Issue", "Score", "DisplayName",
            });
    internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor,
            new java.lang.String[] {
              "InterruptionData",
              "SentimentData",
              "SilenceData",
              "HoldData",
              "EntityMentionData",
              "IntentMatchData",
              "PhraseMatchData",
              "ChannelTag",
              "AnnotationStartBoundary",
              "AnnotationEndBoundary",
              "Data",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor,
            new java.lang.String[] {
              "WordIndex", "TranscriptIndex", "DetailedBoundary",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_contactcenterinsights_v1_Entity_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor,
            new java.lang.String[] {
              "DisplayName", "Type", "Metadata", "Salience", "Sentiment",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_contactcenterinsights_v1_Intent_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor,
            new java.lang.String[] {
              "Id", "DisplayName",
            });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor,
            new java.lang.String[] {
              "PhraseMatcher", "DisplayName",
            });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor,
            new java.lang.String[] {
              "DisplayName",
            });
    internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_contactcenterinsights_v1_SilenceData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_contactcenterinsights_v1_HoldData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor,
            new java.lang.String[] {
              "EntityUniqueId", "Type", "Sentiment",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor,
            new java.lang.String[] {
              "IntentUniqueId",
            });
    internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_contactcenterinsights_v1_SentimentData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor,
            new java.lang.String[] {
              "Magnitude", "Score",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "CreateTime",
              "UpdateTime",
              "State",
              "InputDataConfig",
              "TrainingStats",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor,
            new java.lang.String[] {
              "Medium", "TrainingConversationsCount", "Filter",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_contactcenterinsights_v1_Issue_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor,
            new java.lang.String[] {
              "Name", "DisplayName", "CreateTime", "UpdateTime",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor,
            new java.lang.String[] {
              "AnalyzedConversationsCount", "UnclassifiedConversationsCount", "IssueStats",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor,
            new java.lang.String[] {
              "Issue", "LabeledConversationsCount", "DisplayName",
            });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor,
            new java.lang.String[] {
              "Name",
              "RevisionId",
              "VersionTag",
              "RevisionCreateTime",
              "DisplayName",
              "Type",
              "Active",
              "PhraseMatchRuleGroups",
              "ActivationUpdateTime",
              "RoleMatch",
              "UpdateTime",
            });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor,
            new java.lang.String[] {
              "Type", "PhraseMatchRules",
            });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor,
            new java.lang.String[] {
              "Query", "Negated", "Config",
            });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor,
            new java.lang.String[] {
              "ExactMatchConfig", "Config",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor,
            new java.lang.String[] {
              "CaseSensitive",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "LanguageCode",
              "ConversationTtl",
              "PubsubNotificationSettings",
              "AnalysisConfig",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor,
            new java.lang.String[] {
              "RuntimeIntegrationAnalysisPercentage",
            });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor,
            new java.lang.String[] {
              "ArticleSuggestion",
              "FaqAnswer",
              "SmartReply",
              "SmartComposeSuggestion",
              "DialogflowInteraction",
              "AnnotationId",
              "CreateTime",
              "StartBoundary",
              "EndBoundary",
              "AnswerFeedback",
              "Data",
            });
    internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor,
            new java.lang.String[] {
              "CorrectnessLevel", "Clicked", "Displayed",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor,
            new java.lang.String[] {
              "Title", "Uri", "ConfidenceScore", "Metadata", "QueryRecord", "Source",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor =
        getDescriptor().getMessageTypes().get(33);
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor,
            new java.lang.String[] {
              "Answer", "ConfidenceScore", "Question", "Metadata", "QueryRecord", "Source",
            });
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor =
        getDescriptor().getMessageTypes().get(34);
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor,
            new java.lang.String[] {
              "Reply", "ConfidenceScore", "Metadata", "QueryRecord",
            });
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor =
        getDescriptor().getMessageTypes().get(35);
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor,
            new java.lang.String[] {
              "Suggestion", "ConfidenceScore", "Metadata", "QueryRecord",
            });
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor =
        internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor =
        getDescriptor().getMessageTypes().get(36);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor,
            new java.lang.String[] {
              "DialogflowIntentId", "Confidence",
            });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor =
        getDescriptor().getMessageTypes().get(37);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor,
            new java.lang.String[] {
              "DialogflowParticipantName",
              "UserId",
              "DialogflowParticipant",
              "ObfuscatedExternalUserId",
              "Role",
              "Participant",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
