// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1/resources.proto

package com.google.cloud.contactcenterinsights.v1;

public interface AnnotationBoundaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1.AnnotationBoundary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Deprecated: Use `word_index` for the detailed boundary.
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2 [deprecated = true];</code>
   * @return Whether the timeOffset field is set.
   */
  @java.lang.Deprecated boolean hasTimeOffset();
  /**
   * <pre>
   * Deprecated: Use `word_index` for the detailed boundary.
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2 [deprecated = true];</code>
   * @return The timeOffset.
   */
  @java.lang.Deprecated com.google.protobuf.Duration getTimeOffset();
  /**
   * <pre>
   * Deprecated: Use `word_index` for the detailed boundary.
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.protobuf.DurationOrBuilder getTimeOffsetOrBuilder();

  /**
   * <pre>
   * The word index of this boundary with respect to the first word in the
   * transcript piece. This index starts at zero.
   * </pre>
   *
   * <code>int32 word_index = 3;</code>
   * @return Whether the wordIndex field is set.
   */
  boolean hasWordIndex();
  /**
   * <pre>
   * The word index of this boundary with respect to the first word in the
   * transcript piece. This index starts at zero.
   * </pre>
   *
   * <code>int32 word_index = 3;</code>
   * @return The wordIndex.
   */
  int getWordIndex();

  /**
   * <pre>
   * The index in the sequence of transcribed pieces of the conversation where
   * the boundary is located. This index starts at zero.
   * </pre>
   *
   * <code>int32 transcript_index = 1;</code>
   * @return The transcriptIndex.
   */
  int getTranscriptIndex();

  public com.google.cloud.contactcenterinsights.v1.AnnotationBoundary.DetailedBoundaryCase getDetailedBoundaryCase();
}
