// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1/resources.proto

package com.google.cloud.contactcenterinsights.v1;

public interface ConversationParticipantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1.ConversationParticipant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the Dialogflow participant. Format:
   * projects/{project}/locations/{location}/conversations/{conversation}/participants/{participant}
   * </pre>
   *
   * <code>string dialogflow_participant = 1;</code>
   * @return The dialogflowParticipant.
   */
  java.lang.String getDialogflowParticipant();
  /**
   * <pre>
   * The name of the Dialogflow participant. Format:
   * projects/{project}/locations/{location}/conversations/{conversation}/participants/{participant}
   * </pre>
   *
   * <code>string dialogflow_participant = 1;</code>
   * @return The bytes for dialogflowParticipant.
   */
  com.google.protobuf.ByteString
      getDialogflowParticipantBytes();

  /**
   * <pre>
   * The role of the participant.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1.ConversationParticipant.Role role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <pre>
   * The role of the participant.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1.ConversationParticipant.Role role = 2;</code>
   * @return The role.
   */
  com.google.cloud.contactcenterinsights.v1.ConversationParticipant.Role getRole();
}
