// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1/resources.proto

package com.google.cloud.contactcenterinsights.v1;

public interface IssueAssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1.IssueAssignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the assigned issue.
   * </pre>
   *
   * <code>string issue = 1;</code>
   * @return The issue.
   */
  java.lang.String getIssue();
  /**
   * <pre>
   * Resource name of the assigned issue.
   * </pre>
   *
   * <code>string issue = 1;</code>
   * @return The bytes for issue.
   */
  com.google.protobuf.ByteString
      getIssueBytes();

  /**
   * <pre>
   * Score indicating the likelihood of the issue assignment.
   * currently bounded on [0,1].
   * </pre>
   *
   * <code>double score = 2;</code>
   * @return The score.
   */
  double getScore();
}
