// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1/resources.proto

package com.google.cloud.contactcenterinsights.v1;

public final class ResourcesProto {
  private ResourcesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Analysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_GcsSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Entity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Intent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SilenceData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_HoldData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SentimentData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Issue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5google/cloud/contactcenterinsights/v1/" +
      "resources.proto\022%google.cloud.contactcen" +
      "terinsights.v1\032\037google/api/field_behavio" +
      "r.proto\032\031google/api/resource.proto\032\036goog" +
      "le/protobuf/duration.proto\032\037google/proto" +
      "buf/timestamp.proto\032\034google/api/annotati" +
      "ons.proto\"\304\020\n\014Conversation\022Y\n\rcall_metad" +
      "ata\030\007 \001(\0132@.google.cloud.contactcenterin" +
      "sights.v1.Conversation.CallMetadataH\000\0221\n" +
      "\013expire_time\030\017 \001(\0132\032.google.protobuf.Tim" +
      "estampH\001\022-\n\003ttl\030\020 \001(\0132\031.google.protobuf." +
      "DurationB\003\340A\004H\001\022\021\n\004name\030\001 \001(\tB\003\340A\005\022R\n\013da" +
      "ta_source\030\002 \001(\0132=.google.cloud.contactce" +
      "nterinsights.v1.ConversationDataSource\0224" +
      "\n\013create_time\030\003 \001(\0132\032.google.protobuf.Ti" +
      "mestampB\003\340A\003\0224\n\013update_time\030\004 \001(\0132\032.goog" +
      "le.protobuf.TimestampB\003\340A\003\022.\n\nstart_time" +
      "\030\021 \001(\0132\032.google.protobuf.Timestamp\022\025\n\rla" +
      "nguage_code\030\016 \001(\t\022\020\n\010agent_id\030\005 \001(\t\022O\n\006l" +
      "abels\030\006 \003(\0132?.google.cloud.contactcenter" +
      "insights.v1.Conversation.LabelsEntry\022W\n\n" +
      "transcript\030\010 \001(\0132>.google.cloud.contactc" +
      "enterinsights.v1.Conversation.Transcript" +
      "B\003\340A\003\022O\n\006medium\030\t \001(\0162:.google.cloud.con" +
      "tactcenterinsights.v1.Conversation.Mediu" +
      "mB\003\340A\005\0220\n\010duration\030\n \001(\0132\031.google.protob" +
      "uf.DurationB\003\340A\003\022\027\n\nturn_count\030\013 \001(\005B\003\340A" +
      "\003\022M\n\017latest_analysis\030\014 \001(\0132/.google.clou" +
      "d.contactcenterinsights.v1.AnalysisB\003\340A\003" +
      "\022Z\n\023runtime_annotations\030\r \003(\01328.google.c" +
      "loud.contactcenterinsights.v1.RuntimeAnn" +
      "otationB\003\340A\003\022k\n\022dialogflow_intents\030\022 \003(\013" +
      "2J.google.cloud.contactcenterinsights.v1" +
      ".Conversation.DialogflowIntentsEntryB\003\340A" +
      "\003\032?\n\014CallMetadata\022\030\n\020customer_channel\030\001 " +
      "\001(\005\022\025\n\ragent_channel\030\002 \001(\005\032\265\004\n\nTranscrip" +
      "t\022m\n\023transcript_segments\030\001 \003(\0132P.google." +
      "cloud.contactcenterinsights.v1.Conversat" +
      "ion.Transcript.TranscriptSegment\032\267\003\n\021Tra" +
      "nscriptSegment\022\014\n\004text\030\001 \001(\t\022\022\n\nconfiden" +
      "ce\030\002 \001(\002\022h\n\005words\030\003 \003(\0132Y.google.cloud.c" +
      "ontactcenterinsights.v1.Conversation.Tra" +
      "nscript.TranscriptSegment.WordInfo\022\025\n\rla" +
      "nguage_code\030\004 \001(\t\022\023\n\013channel_tag\030\005 \001(\005\022[" +
      "\n\023segment_participant\030\t \001(\0132>.google.clo" +
      "ud.contactcenterinsights.v1.Conversation" +
      "Participant\032\214\001\n\010WordInfo\022/\n\014start_offset" +
      "\030\001 \001(\0132\031.google.protobuf.Duration\022-\n\nend" +
      "_offset\030\002 \001(\0132\031.google.protobuf.Duration" +
      "\022\014\n\004word\030\003 \001(\t\022\022\n\nconfidence\030\004 \001(\002\032-\n\013La" +
      "belsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\032q\n\026DialogflowIntentsEntry\022\013\n\003key\030\001 \001(\t" +
      "\022F\n\005value\030\002 \001(\01327.google.cloud.contactce" +
      "nterinsights.v1.DialogflowIntent:\0028\001\":\n\006" +
      "Medium\022\026\n\022MEDIUM_UNSPECIFIED\020\000\022\016\n\nPHONE_" +
      "CALL\020\001\022\010\n\004CHAT\020\002:|\352Ay\n1contactcenterinsi" +
      "ghts.googleapis.com/Conversation\022Dprojec" +
      "ts/{project}/locations/{location}/conver" +
      "sations/{conversation}B\n\n\010metadataB\014\n\nex" +
      "piration\"\357\002\n\010Analysis\022\021\n\004name\030\001 \001(\tB\003\340A\005" +
      "\0225\n\014request_time\030\002 \001(\0132\032.google.protobuf" +
      ".TimestampB\003\340A\003\0224\n\013create_time\030\003 \001(\0132\032.g" +
      "oogle.protobuf.TimestampB\003\340A\003\022S\n\017analysi" +
      "s_result\030\007 \001(\01325.google.cloud.contactcen" +
      "terinsights.v1.AnalysisResultB\003\340A\003:\215\001\352A\211" +
      "\001\n-contactcenterinsights.googleapis.com/" +
      "Analysis\022Xprojects/{project}/locations/{" +
      "location}/conversations/{conversation}/a" +
      "nalyses/{analysis}\"\300\001\n\026ConversationDataS" +
      "ource\022F\n\ngcs_source\030\001 \001(\01320.google.cloud" +
      ".contactcenterinsights.v1.GcsSourceH\000\022T\n" +
      "\021dialogflow_source\030\003 \001(\01327.google.cloud." +
      "contactcenterinsights.v1.DialogflowSourc" +
      "eH\000B\010\n\006source\";\n\tGcsSource\022\021\n\taudio_uri\030" +
      "\001 \001(\t\022\033\n\016transcript_uri\030\002 \001(\tB\003\340A\005\"K\n\020Di" +
      "alogflowSource\022$\n\027dialogflow_conversatio" +
      "n\030\001 \001(\tB\003\340A\003\022\021\n\taudio_uri\030\003 \001(\t\"\306\010\n\016Anal" +
      "ysisResult\022l\n\026call_analysis_metadata\030\002 \001" +
      "(\0132J.google.cloud.contactcenterinsights." +
      "v1.AnalysisResult.CallAnalysisMetadataH\000" +
      "\022,\n\010end_time\030\001 \001(\0132\032.google.protobuf.Tim" +
      "estamp\032\213\007\n\024CallAnalysisMetadata\022J\n\013annot" +
      "ations\030\002 \003(\01325.google.cloud.contactcente" +
      "rinsights.v1.CallAnnotation\022j\n\010entities\030" +
      "\003 \003(\0132X.google.cloud.contactcenterinsigh" +
      "ts.v1.AnalysisResult.CallAnalysisMetadat" +
      "a.EntitiesEntry\022U\n\nsentiments\030\004 \003(\0132A.go" +
      "ogle.cloud.contactcenterinsights.v1.Conv" +
      "ersationLevelSentiment\022h\n\007intents\030\006 \003(\0132" +
      "W.google.cloud.contactcenterinsights.v1." +
      "AnalysisResult.CallAnalysisMetadata.Inte" +
      "ntsEntry\022w\n\017phrase_matchers\030\007 \003(\0132^.goog" +
      "le.cloud.contactcenterinsights.v1.Analys" +
      "isResult.CallAnalysisMetadata.PhraseMatc" +
      "hersEntry\022S\n\022issue_model_result\030\010 \001(\01327." +
      "google.cloud.contactcenterinsights.v1.Is" +
      "sueModelResult\032^\n\rEntitiesEntry\022\013\n\003key\030\001" +
      " \001(\t\022<\n\005value\030\002 \001(\0132-.google.cloud.conta" +
      "ctcenterinsights.v1.Entity:\0028\001\032]\n\014Intent" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022<\n\005value\030\002 \001(\0132-.goo" +
      "gle.cloud.contactcenterinsights.v1.Inten" +
      "t:\0028\001\032m\n\023PhraseMatchersEntry\022\013\n\003key\030\001 \001(" +
      "\t\022E\n\005value\030\002 \001(\01326.google.cloud.contactc" +
      "enterinsights.v1.PhraseMatchData:\0028\001B\n\n\010" +
      "metadata\"o\n\020IssueModelResult\022\023\n\013issue_mo" +
      "del\030\001 \001(\t\022F\n\006issues\030\002 \003(\01326.google.cloud" +
      ".contactcenterinsights.v1.IssueAssignmen" +
      "t\"\177\n\032ConversationLevelSentiment\022\023\n\013chann" +
      "el_tag\030\001 \001(\005\022L\n\016sentiment_data\030\002 \001(\01324.g" +
      "oogle.cloud.contactcenterinsights.v1.Sen" +
      "timentData\"/\n\017IssueAssignment\022\r\n\005issue\030\001" +
      " \001(\t\022\r\n\005score\030\002 \001(\001\"\242\006\n\016CallAnnotation\022T" +
      "\n\021interruption_data\030\n \001(\01327.google.cloud" +
      ".contactcenterinsights.v1.InterruptionDa" +
      "taH\000\022N\n\016sentiment_data\030\013 \001(\01324.google.cl" +
      "oud.contactcenterinsights.v1.SentimentDa" +
      "taH\000\022J\n\014silence_data\030\014 \001(\01322.google.clou" +
      "d.contactcenterinsights.v1.SilenceDataH\000" +
      "\022D\n\thold_data\030\r \001(\0132/.google.cloud.conta" +
      "ctcenterinsights.v1.HoldDataH\000\022W\n\023entity" +
      "_mention_data\030\017 \001(\01328.google.cloud.conta" +
      "ctcenterinsights.v1.EntityMentionDataH\000\022" +
      "S\n\021intent_match_data\030\020 \001(\01326.google.clou" +
      "d.contactcenterinsights.v1.IntentMatchDa" +
      "taH\000\022S\n\021phrase_match_data\030\021 \001(\01326.google" +
      ".cloud.contactcenterinsights.v1.PhraseMa" +
      "tchDataH\000\022\023\n\013channel_tag\030\001 \001(\005\022\\\n\031annota" +
      "tion_start_boundary\030\004 \001(\01329.google.cloud" +
      ".contactcenterinsights.v1.AnnotationBoun" +
      "dary\022Z\n\027annotation_end_boundary\030\005 \001(\01329." +
      "google.cloud.contactcenterinsights.v1.An" +
      "notationBoundaryB\006\n\004data\"Y\n\022AnnotationBo" +
      "undary\022\024\n\nword_index\030\003 \001(\005H\000\022\030\n\020transcri" +
      "pt_index\030\001 \001(\005B\023\n\021detailed_boundary\"\200\004\n\006" +
      "Entity\022\024\n\014display_name\030\001 \001(\t\022@\n\004type\030\002 \001" +
      "(\01622.google.cloud.contactcenterinsights." +
      "v1.Entity.Type\022M\n\010metadata\030\003 \003(\0132;.googl" +
      "e.cloud.contactcenterinsights.v1.Entity." +
      "MetadataEntry\022\020\n\010salience\030\004 \001(\002\022G\n\tsenti" +
      "ment\030\005 \001(\01324.google.cloud.contactcenteri" +
      "nsights.v1.SentimentData\032/\n\rMetadataEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\302\001\n\004Ty" +
      "pe\022\024\n\020TYPE_UNSPECIFIED\020\000\022\n\n\006PERSON\020\001\022\014\n\010" +
      "LOCATION\020\002\022\020\n\014ORGANIZATION\020\003\022\t\n\005EVENT\020\004\022" +
      "\017\n\013WORK_OF_ART\020\005\022\021\n\rCONSUMER_GOOD\020\006\022\t\n\005O" +
      "THER\020\007\022\020\n\014PHONE_NUMBER\020\t\022\013\n\007ADDRESS\020\n\022\010\n" +
      "\004DATE\020\013\022\n\n\006NUMBER\020\014\022\t\n\005PRICE\020\r\"*\n\006Intent" +
      "\022\n\n\002id\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\"?\n\017Ph" +
      "raseMatchData\022\026\n\016phrase_matcher\030\001 \001(\t\022\024\n" +
      "\014display_name\030\002 \001(\t\"(\n\020DialogflowIntent\022" +
      "\024\n\014display_name\030\001 \001(\t\"\022\n\020InterruptionDat" +
      "a\"\r\n\013SilenceData\"\n\n\010HoldData\"\217\002\n\021EntityM" +
      "entionData\022\030\n\020entity_unique_id\030\001 \001(\t\022R\n\004" +
      "type\030\002 \001(\0162D.google.cloud.contactcenteri" +
      "nsights.v1.EntityMentionData.MentionType" +
      "\022G\n\tsentiment\030\003 \001(\01324.google.cloud.conta" +
      "ctcenterinsights.v1.SentimentData\"C\n\013Men" +
      "tionType\022\034\n\030MENTION_TYPE_UNSPECIFIED\020\000\022\n" +
      "\n\006PROPER\020\001\022\n\n\006COMMON\020\002\"+\n\017IntentMatchDat" +
      "a\022\030\n\020intent_unique_id\030\001 \001(\t\"1\n\rSentiment" +
      "Data\022\021\n\tmagnitude\030\001 \001(\002\022\r\n\005score\030\002 \001(\002\"\236" +
      "\006\n\nIssueModel\022\021\n\004name\030\001 \001(\tB\003\340A\005\022\024\n\014disp" +
      "lay_name\030\002 \001(\t\0224\n\013create_time\030\003 \001(\0132\032.go" +
      "ogle.protobuf.TimestampB\003\340A\003\0224\n\013update_t" +
      "ime\030\004 \001(\0132\032.google.protobuf.TimestampB\003\340" +
      "A\003\022K\n\005state\030\005 \001(\01627.google.cloud.contact" +
      "centerinsights.v1.IssueModel.StateB\003\340A\003\022" +
      "\\\n\021input_data_config\030\006 \001(\0132A.google.clou" +
      "d.contactcenterinsights.v1.IssueModel.In" +
      "putDataConfig\022[\n\016training_stats\030\007 \001(\0132;." +
      "google.cloud.contactcenterinsights.v1.Is" +
      "sueModelLabelStatsB\006\340A\003\340A\005\032\215\001\n\017InputData" +
      "Config\022O\n\006medium\030\001 \001(\0162:.google.cloud.co" +
      "ntactcenterinsights.v1.Conversation.Medi" +
      "umB\003\340A\002\022)\n\034training_conversations_count\030" +
      "\002 \001(\003B\003\340A\003\"j\n\005State\022\025\n\021STATE_UNSPECIFIED" +
      "\020\000\022\016\n\nUNDEPLOYED\020\001\022\r\n\tDEPLOYING\020\002\022\014\n\010DEP" +
      "LOYED\020\003\022\017\n\013UNDEPLOYING\020\004\022\014\n\010DELETING\020\005:w" +
      "\352At\n/contactcenterinsights.googleapis.co" +
      "m/IssueModel\022Aprojects/{project}/locatio" +
      "ns/{location}/issueModels/{issue_model}\"" +
      "\240\002\n\005Issue\022\021\n\004name\030\001 \001(\tB\003\340A\005\022\024\n\014display_" +
      "name\030\002 \001(\t\0224\n\013create_time\030\003 \001(\0132\032.google" +
      ".protobuf.TimestampB\003\340A\003\0224\n\013update_time\030" +
      "\004 \001(\0132\032.google.protobuf.TimestampB\003\340A\003:\201" +
      "\001\352A~\n*contactcenterinsights.googleapis.c" +
      "om/Issue\022Pprojects/{project}/locations/{" +
      "location}/issueModels/{issue_model}/issu" +
      "es/{issue}\"\205\003\n\024IssueModelLabelStats\022$\n\034a" +
      "nalyzed_conversations_count\030\001 \001(\003\022(\n unc" +
      "lassified_conversations_count\030\002 \001(\003\022`\n\013i" +
      "ssue_stats\030\003 \003(\0132K.google.cloud.contactc" +
      "enterinsights.v1.IssueModelLabelStats.Is" +
      "sueStatsEntry\032@\n\nIssueStats\022\r\n\005issue\030\001 \001" +
      "(\t\022#\n\033labeled_conversations_count\030\002 \001(\003\032" +
      "y\n\017IssueStatsEntry\022\013\n\003key\030\001 \001(\t\022U\n\005value" +
      "\030\002 \001(\0132F.google.cloud.contactcenterinsig" +
      "hts.v1.IssueModelLabelStats.IssueStats:\002" +
      "8\001\"\335\005\n\rPhraseMatcher\022\014\n\004name\030\001 \001(\t\022\033\n\013re" +
      "vision_id\030\002 \001(\tB\006\340A\005\340A\003\022\023\n\013version_tag\030\003" +
      " \001(\t\022=\n\024revision_create_time\030\004 \001(\0132\032.goo" +
      "gle.protobuf.TimestampB\003\340A\003\022\024\n\014display_n" +
      "ame\030\005 \001(\t\022Y\n\004type\030\006 \001(\0162F.google.cloud.c" +
      "ontactcenterinsights.v1.PhraseMatcher.Ph" +
      "raseMatcherTypeB\003\340A\002\022\016\n\006active\030\007 \001(\010\022]\n\030" +
      "phrase_match_rule_groups\030\010 \003(\0132;.google." +
      "cloud.contactcenterinsights.v1.PhraseMat" +
      "chRuleGroup\022?\n\026activation_update_time\030\t " +
      "\001(\0132\032.google.protobuf.TimestampB\003\340A\003\022W\n\n" +
      "role_match\030\n \001(\0162C.google.cloud.contactc" +
      "enterinsights.v1.ConversationParticipant" +
      ".Role\"P\n\021PhraseMatcherType\022#\n\037PHRASE_MAT" +
      "CHER_TYPE_UNSPECIFIED\020\000\022\n\n\006ALL_OF\020\001\022\n\n\006A" +
      "NY_OF\020\002:\200\001\352A}\n2contactcenterinsights.goo" +
      "gleapis.com/PhraseMatcher\022Gprojects/{pro" +
      "ject}/locations/{location}/phraseMatcher" +
      "s/{phrase_matcher}\"\265\002\n\024PhraseMatchRuleGr" +
      "oup\022g\n\004type\030\001 \001(\0162T.google.cloud.contact" +
      "centerinsights.v1.PhraseMatchRuleGroup.P" +
      "hraseMatchRuleGroupTypeB\003\340A\002\022R\n\022phrase_m" +
      "atch_rules\030\002 \003(\01326.google.cloud.contactc" +
      "enterinsights.v1.PhraseMatchRule\"`\n\030Phra" +
      "seMatchRuleGroupType\022,\n(PHRASE_MATCH_RUL" +
      "E_GROUP_TYPE_UNSPECIFIED\020\000\022\n\n\006ALL_OF\020\001\022\n" +
      "\n\006ANY_OF\020\002\"\204\001\n\017PhraseMatchRule\022\022\n\005query\030" +
      "\001 \001(\tB\003\340A\002\022\017\n\007negated\030\002 \001(\010\022L\n\006config\030\003 " +
      "\001(\0132<.google.cloud.contactcenterinsights" +
      ".v1.PhraseMatchRuleConfig\"x\n\025PhraseMatch" +
      "RuleConfig\022U\n\022exact_match_config\030\001 \001(\01327" +
      ".google.cloud.contactcenterinsights.v1.E" +
      "xactMatchConfigH\000B\010\n\006config\"*\n\020ExactMatc" +
      "hConfig\022\026\n\016case_sensitive\030\001 \001(\010\"\221\005\n\010Sett" +
      "ings\022\021\n\004name\030\001 \001(\tB\003\340A\005\0224\n\013create_time\030\002" +
      " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n" +
      "\013update_time\030\003 \001(\0132\032.google.protobuf.Tim" +
      "estampB\003\340A\003\022\025\n\rlanguage_code\030\004 \001(\t\0223\n\020co" +
      "nversation_ttl\030\005 \001(\0132\031.google.protobuf.D" +
      "uration\022u\n\034pubsub_notification_settings\030" +
      "\006 \003(\0132O.google.cloud.contactcenterinsigh" +
      "ts.v1.Settings.PubsubNotificationSetting" +
      "sEntry\022W\n\017analysis_config\030\007 \001(\0132>.google" +
      ".cloud.contactcenterinsights.v1.Settings" +
      ".AnalysisConfig\032A\n\016AnalysisConfig\022/\n\'run" +
      "time_integration_analysis_percentage\030\001 \001" +
      "(\001\032A\n\037PubsubNotificationSettingsEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:d\352Aa\n-cont" +
      "actcenterinsights.googleapis.com/Setting" +
      "s\0220projects/{project}/locations/{locatio" +
      "n}/settings\"\230\006\n\021RuntimeAnnotation\022Z\n\022art" +
      "icle_suggestion\030\006 \001(\0132<.google.cloud.con" +
      "tactcenterinsights.v1.ArticleSuggestionD" +
      "ataH\000\022J\n\nfaq_answer\030\007 \001(\01324.google.cloud" +
      ".contactcenterinsights.v1.FaqAnswerDataH" +
      "\000\022L\n\013smart_reply\030\010 \001(\01325.google.cloud.co" +
      "ntactcenterinsights.v1.SmartReplyDataH\000\022" +
      "e\n\030smart_compose_suggestion\030\t \001(\0132A.goog" +
      "le.cloud.contactcenterinsights.v1.SmartC" +
      "omposeSuggestionDataH\000\022b\n\026dialogflow_int" +
      "eraction\030\n \001(\0132@.google.cloud.contactcen" +
      "terinsights.v1.DialogflowInteractionData" +
      "H\000\022\025\n\rannotation_id\030\001 \001(\t\022/\n\013create_time" +
      "\030\002 \001(\0132\032.google.protobuf.Timestamp\022Q\n\016st" +
      "art_boundary\030\003 \001(\01329.google.cloud.contac" +
      "tcenterinsights.v1.AnnotationBoundary\022O\n" +
      "\014end_boundary\030\004 \001(\01329.google.cloud.conta" +
      "ctcenterinsights.v1.AnnotationBoundary\022N" +
      "\n\017answer_feedback\030\005 \001(\01325.google.cloud.c" +
      "ontactcenterinsights.v1.AnswerFeedbackB\006" +
      "\n\004data\"\211\002\n\016AnswerFeedback\022a\n\021correctness" +
      "_level\030\001 \001(\0162F.google.cloud.contactcente" +
      "rinsights.v1.AnswerFeedback.CorrectnessL" +
      "evel\022\017\n\007clicked\030\002 \001(\010\022\021\n\tdisplayed\030\003 \001(\010" +
      "\"p\n\020CorrectnessLevel\022!\n\035CORRECTNESS_LEVE" +
      "L_UNSPECIFIED\020\000\022\017\n\013NOT_CORRECT\020\001\022\025\n\021PART" +
      "IALLY_CORRECT\020\002\022\021\n\rFULLY_CORRECT\020\003\"\202\002\n\025A" +
      "rticleSuggestionData\022\r\n\005title\030\001 \001(\t\022\013\n\003u" +
      "ri\030\002 \001(\t\022\030\n\020confidence_score\030\003 \001(\002\022\\\n\010me" +
      "tadata\030\004 \003(\0132J.google.cloud.contactcente" +
      "rinsights.v1.ArticleSuggestionData.Metad" +
      "ataEntry\022\024\n\014query_record\030\005 \001(\t\022\016\n\006source" +
      "\030\006 \001(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\"\370\001\n\rFaqAnswerData\022\016\n\006ans" +
      "wer\030\001 \001(\t\022\030\n\020confidence_score\030\002 \001(\002\022\020\n\010q" +
      "uestion\030\003 \001(\t\022T\n\010metadata\030\004 \003(\0132B.google" +
      ".cloud.contactcenterinsights.v1.FaqAnswe" +
      "rData.MetadataEntry\022\024\n\014query_record\030\005 \001(" +
      "\t\022\016\n\006source\030\006 \001(\t\032/\n\rMetadataEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\327\001\n\016SmartRepl" +
      "yData\022\r\n\005reply\030\001 \001(\t\022\030\n\020confidence_score" +
      "\030\002 \001(\001\022U\n\010metadata\030\003 \003(\0132C.google.cloud." +
      "contactcenterinsights.v1.SmartReplyData." +
      "MetadataEntry\022\024\n\014query_record\030\004 \001(\t\032/\n\rM" +
      "etadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"\364\001\n\032SmartComposeSuggestionData\022\022\n\ns" +
      "uggestion\030\001 \001(\t\022\030\n\020confidence_score\030\002 \001(" +
      "\001\022a\n\010metadata\030\003 \003(\0132O.google.cloud.conta" +
      "ctcenterinsights.v1.SmartComposeSuggesti" +
      "onData.MetadataEntry\022\024\n\014query_record\030\004 \001" +
      "(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"M\n\031DialogflowInteractionData" +
      "\022\034\n\024dialogflow_intent_id\030\001 \001(\t\022\022\n\nconfid" +
      "ence\030\002 \001(\002\"\346\002\n\027ConversationParticipant\022Q" +
      "\n\033dialogflow_participant_name\030\005 \001(\tB*\372A\'" +
      "\n%dialogflow.googleapis.com/ParticipantH" +
      "\000\022\021\n\007user_id\030\006 \001(\tH\000\022\"\n\026dialogflow_parti" +
      "cipant\030\001 \001(\tB\002\030\001\022Q\n\004role\030\002 \001(\0162C.google." +
      "cloud.contactcenterinsights.v1.Conversat" +
      "ionParticipant.Role\"_\n\004Role\022\024\n\020ROLE_UNSP" +
      "ECIFIED\020\000\022\017\n\013HUMAN_AGENT\020\001\022\023\n\017AUTOMATED_" +
      "AGENT\020\002\022\014\n\010END_USER\020\003\022\r\n\tANY_AGENT\020\004B\r\n\013" +
      "participantB\354\003\n)com.google.cloud.contact" +
      "centerinsights.v1B\016ResourcesProtoP\001ZZgoo" +
      "gle.golang.org/genproto/googleapis/cloud" +
      "/contactcenterinsights/v1;contactcenteri" +
      "nsights\252\002%Google.Cloud.ContactCenterInsi" +
      "ghts.V1\312\002%Google\\Cloud\\ContactCenterInsi" +
      "ghts\\V1\352\002(Google::Cloud::ContactCenterIn" +
      "sights::V1\352A\324\001\n%dialogflow.googleapis.co" +
      "m/Participant\022Jprojects/{project}/conver" +
      "sations/{conversation}/participants/{par" +
      "ticipant}\022_projects/{project}/locations/" +
      "{location}/conversations/{conversation}/" +
      "participants/{participant}b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor,
        new java.lang.String[] { "CallMetadata", "ExpireTime", "Ttl", "Name", "DataSource", "CreateTime", "UpdateTime", "StartTime", "LanguageCode", "AgentId", "Labels", "Transcript", "Medium", "Duration", "TurnCount", "LatestAnalysis", "RuntimeAnnotations", "DialogflowIntents", "Metadata", "Expiration", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_CallMetadata_descriptor,
        new java.lang.String[] { "CustomerChannel", "AgentChannel", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor,
        new java.lang.String[] { "TranscriptSegments", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor,
        new java.lang.String[] { "Text", "Confidence", "Words", "LanguageCode", "ChannelTag", "SegmentParticipant", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor,
        new java.lang.String[] { "StartOffset", "EndOffset", "Word", "Confidence", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor.getNestedTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Conversation_descriptor.getNestedTypes().get(3);
    internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Conversation_DialogflowIntentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Analysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Analysis_descriptor,
        new java.lang.String[] { "Name", "RequestTime", "CreateTime", "AnalysisResult", });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ConversationDataSource_descriptor,
        new java.lang.String[] { "GcsSource", "DialogflowSource", "Source", });
    internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_contactcenterinsights_v1_GcsSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_GcsSource_descriptor,
        new java.lang.String[] { "AudioUri", "TranscriptUri", });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_DialogflowSource_descriptor,
        new java.lang.String[] { "DialogflowConversation", "AudioUri", });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor,
        new java.lang.String[] { "CallAnalysisMetadata", "EndTime", "Metadata", });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor,
        new java.lang.String[] { "Annotations", "Entities", "Sentiments", "Intents", "PhraseMatchers", "IssueModelResult", });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_IntentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_descriptor.getNestedTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnalysisResult_CallAnalysisMetadata_PhraseMatchersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelResult_descriptor,
        new java.lang.String[] { "IssueModel", "Issues", });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ConversationLevelSentiment_descriptor,
        new java.lang.String[] { "ChannelTag", "SentimentData", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueAssignment_descriptor,
        new java.lang.String[] { "Issue", "Score", });
    internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_CallAnnotation_descriptor,
        new java.lang.String[] { "InterruptionData", "SentimentData", "SilenceData", "HoldData", "EntityMentionData", "IntentMatchData", "PhraseMatchData", "ChannelTag", "AnnotationStartBoundary", "AnnotationEndBoundary", "Data", });
    internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnnotationBoundary_descriptor,
        new java.lang.String[] { "WordIndex", "TranscriptIndex", "DetailedBoundary", });
    internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_contactcenterinsights_v1_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor,
        new java.lang.String[] { "DisplayName", "Type", "Metadata", "Salience", "Sentiment", });
    internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Entity_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Entity_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_contactcenterinsights_v1_Intent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Intent_descriptor,
        new java.lang.String[] { "Id", "DisplayName", });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchData_descriptor,
        new java.lang.String[] { "PhraseMatcher", "DisplayName", });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_DialogflowIntent_descriptor,
        new java.lang.String[] { "DisplayName", });
    internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_InterruptionData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_contactcenterinsights_v1_SilenceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SilenceData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_contactcenterinsights_v1_HoldData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_HoldData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_EntityMentionData_descriptor,
        new java.lang.String[] { "EntityUniqueId", "Type", "Sentiment", });
    internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IntentMatchData_descriptor,
        new java.lang.String[] { "IntentUniqueId", });
    internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_contactcenterinsights_v1_SentimentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SentimentData_descriptor,
        new java.lang.String[] { "Magnitude", "Score", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "CreateTime", "UpdateTime", "State", "InputDataConfig", "TrainingStats", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_IssueModel_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModel_InputDataConfig_descriptor,
        new java.lang.String[] { "Medium", "TrainingConversationsCount", });
    internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_contactcenterinsights_v1_Issue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Issue_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "CreateTime", "UpdateTime", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor,
        new java.lang.String[] { "AnalyzedConversationsCount", "UnclassifiedConversationsCount", "IssueStats", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStats_descriptor,
        new java.lang.String[] { "Issue", "LabeledConversationsCount", });
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_IssueModelLabelStats_IssueStatsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_PhraseMatcher_descriptor,
        new java.lang.String[] { "Name", "RevisionId", "VersionTag", "RevisionCreateTime", "DisplayName", "Type", "Active", "PhraseMatchRuleGroups", "ActivationUpdateTime", "RoleMatch", });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleGroup_descriptor,
        new java.lang.String[] { "Type", "PhraseMatchRules", });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRule_descriptor,
        new java.lang.String[] { "Query", "Negated", "Config", });
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_PhraseMatchRuleConfig_descriptor,
        new java.lang.String[] { "ExactMatchConfig", "Config", });
    internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ExactMatchConfig_descriptor,
        new java.lang.String[] { "CaseSensitive", });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor,
        new java.lang.String[] { "Name", "CreateTime", "UpdateTime", "LanguageCode", "ConversationTtl", "PubsubNotificationSettings", "AnalysisConfig", });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Settings_AnalysisConfig_descriptor,
        new java.lang.String[] { "RuntimeIntegrationAnalysisPercentage", });
    internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_Settings_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_Settings_PubsubNotificationSettingsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_RuntimeAnnotation_descriptor,
        new java.lang.String[] { "ArticleSuggestion", "FaqAnswer", "SmartReply", "SmartComposeSuggestion", "DialogflowInteraction", "AnnotationId", "CreateTime", "StartBoundary", "EndBoundary", "AnswerFeedback", "Data", });
    internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_AnswerFeedback_descriptor,
        new java.lang.String[] { "CorrectnessLevel", "Clicked", "Displayed", });
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor,
        new java.lang.String[] { "Title", "Uri", "ConfidenceScore", "Metadata", "QueryRecord", "Source", });
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ArticleSuggestionData_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor,
        new java.lang.String[] { "Answer", "ConfidenceScore", "Question", "Metadata", "QueryRecord", "Source", });
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_FaqAnswerData_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor,
        new java.lang.String[] { "Reply", "ConfidenceScore", "Metadata", "QueryRecord", });
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SmartReplyData_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor,
        new java.lang.String[] { "Suggestion", "ConfidenceScore", "Metadata", "QueryRecord", });
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_SmartComposeSuggestionData_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_DialogflowInteractionData_descriptor,
        new java.lang.String[] { "DialogflowIntentId", "Confidence", });
    internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1_ConversationParticipant_descriptor,
        new java.lang.String[] { "DialogflowParticipantName", "UserId", "DialogflowParticipant", "Role", "Participant", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
